### ISSUE TITLE
group layer functionality for  addLegendImage not working

### ISSUE THREAD

**Issue by Abhishek-Kar** [tomroh/leaflegend#45]
Here is the code snippet

  addLegendImage(
      images = c("http://leafletjs.com/examples/custom-icons/leaf-green.png"),
      labels = "",
      labelStyle = "font-size: 12px; horizontal-align: middle;",
      width = 350,
      height = 350,
      group ="AllTime"
  ) %>%

addLayersControl(
    overlayGroups =c("AllTime",
                     "TimeA: Li850/MA55: UV.BC",
                     "TimeB: Li850/MA55: UV.BC",
...
                     ),
    options = layersControlOptions(collapsed = F)
  )

As you can see in the attached screenshot, even when the group "AllTime" is deselected, the image remains

![Screen Shot 2021-11-28 at 11 59 17 PM](https://user-images.githubusercontent.com/34145330/143811409-7336fa6d-66db-4c21-9076-11a62f193a37.png)

**Comment by tomroh** [comment]
Some special characters do not work in the "groups" name:

```r
leaflet() |> 
  addTiles() |> 
  addLegendImage(
    images = c("http://leafletjs.com/examples/custom-icons/leaf-green.png"),
    labels = "",
    labelStyle = "font-size: 12px; horizontal-align: middle;",
    width = 350,
    height = 350,
    group ="AllTime"
  ) |>
  
  addLayersControl(
    overlayGroups =c("AllTime",
                     "TimeA Li850MA55 UV.BC",
                     "TimeB Li850MA55 UV.BC"
    ),
    options = layersControlOptions(collapsed = F)
  )
```

**Comment by tomroh** [comment]
If you use the above code with the special characters removed, does it work? The example worked for me.

**Comment by Abhishek-Kar** [comment]
Yes, it does. I have tried it after removing space & dots from the group
name.
Thank you for creating an amazing package and your problem solving for a
bumbling idiot like me :)

Warm regards,
Abhishek

**Comment by tomroh** [comment]
No problem. Thanks for raising the issue. I'm going to keep this issue open for now because I believe base ```leaflet``` groups can have special characters. The javascript code that adds the hide/show functionality for legend groups needs to be modified.

**Comment by w148smh** [comment]
It did work in this example (and my code) with all spaces removed! Awesome package and **much** needed. THANK YOU

**Comment by tomroh** [comment]
Special characters are now allowed for group names. 1aff4742da5ac5cad2eabebd7353628315391bfe

**Comment by marcusyoung** [comment]
I have this problems with  the latest CRAN version when I have underscores in the group name. For example, hideGroup does not remove the legend. Works fine without the underscores. Has this problem resurfaced ?

**Comment by marcusyoung** [comment]
Actually, on further testing, hideGroup doesn't work whether the name has special characters or not.

**Comment by tomroh** [comment]
Actually, hideGroup works as well:

```
leaflet() %>%
  addTiles() %>%
  addLegendNumeric(
    pal = numPal,
    values = quakes$depth,
    position = 'topright',
    title = 'addLegendNumeric',
    group = 'Numeric Data'
  ) %>%
  addLegendQuantile(
    pal = quantPal,
    values = quakes$mag,
    position = 'topright',
    title = 'addLegendQuantile',
    group = 'Quantile'
  ) %>%
  addLegendBin(
    pal = binPal,
    values = quakes$mag,
    position = 'bottomleft',
    title = 'addLegendBin',
    group = 'Bin'
  ) %>%
  addLayersControl(
    baseGroups = c('Numeric Data', 'Quantile'),  overlayGroups = c('Bin'),
    position = 'bottomright'
  ) %>%
  leaflet::hideGroup('Bin') 
```

**Comment by marcusyoung** [comment]
This is an example of code that didn't work for me:

```
observeEvent({
    aadf_edges_filtered()
  }, {
    if (input$aadf_edges == TRUE &&
        input$aadf_region != "" && input$aadf_year != "") {
      leafletProxy("map", data = aadf_edges_filtered()) %>%
        clearGroup("mg_aadf_edges") %>%
        leaflet.extras2::addSpinner() %>%
        leaflet.extras2::startSpinner(options = list("lines" = 12, "length" = 15)) %>%
        addPolylines(
          options = pathOptions(pane = "mp_aadf_edges"),
          group = "mg_aadf_edges",
          layerId = ~ link_id,
          weight = (
            aadf_edges_filtered()$selected_class / map_edges_scaling_factor()
          ),
          color = "firebrick",
          opacity = 0.5,
          highlightOptions = highlightOptions(
            color = "firebrick",
            bringToFront = F,
            opacity = 0.9
          )
        ) %>%
        leaflegend::addLegendSize(
          group = "mg_aadf_edges",
          color = "firebrick",
          shape = "rect",
          baseSize = mean((
            aadf_edges_filtered()$selected_class / map_edges_scaling_factor()
          )
          ),
          values = aadf_edges_filtered()$selected_class,
          layerId = 1,
          fillOpacity = 0.5,
          strokeWidth = 0,
          title = aadf_edges_legend_title(),
          position = "topleft",
          breaks = 4
        ) %>%
        leaflet.extras2::stopSpinner()
    }
  })
```

Then, this code should hide or show the group depending on a checkbox state. It hid or showed the polyline layer but did nothing for the legend.
```
observeEvent(input$aadf_edges, {
    if (input$aadf_edges == TRUE) {
      leafletProxy("map") %>%
        showGroup("mg_aadf_edges")
    } else {
      leafletProxy("map") %>%
        hideGroup("mg_aadf_edges")
    }
})
```

**Comment by shum461** [comment]
Underscores and other special characters in the name of the hidegroup used to be an issue. It may be resolved now

**Comment by tomroh** [comment]
Underscores weren't working moved this to issue #75
