### ISSUE TITLE
adjust labels of addLegendSize 

### ISSUE THREAD

**Issue by mtennekes** [tomroh/leaflegend#60]
I'm working on implementing leaflegend in tmap v4 (https://github.com/r-tmap/tmap/issues/699). One important question:

Can the legend labels be specified in `addLegendSize`? I'd like to be able to specify any text (e.g. "Very large", "Large", "Medium", "Small") for the symbol sizes.

**Comment by tomroh** [comment]
```labelStyle``` takes css styling input. I think what you are looking for is:

```
library(leaflet)
library(leaflegend)
data(quakes)
fontSize <- c('small' = 10, 'medium' = 20 , 'large' = 30)
leaflet(quakes) |> addLegendSize(values = ~depth, color = 'black', shape  = 'plus', 
    breaks = 3, labelStyle = sprintf('font-size: %dpx;vertical-align: middle;', 
      fontSize['medium'])) |> 
  addLegendSize(values = ~depth, color = 'black', shape  = 'plus', 
    breaks = 3, labelStyle = sprintf('font-size: %dpx;vertical-align: middle;', 
      fontSize['large']),
    orientation = 'horizontal')
```

**Comment by tomroh** [comment]
- [ ] add option to pass named vector of breaks

**Comment by mtennekes** [comment]
Yes, indeed. That would be great! 

From how I understand your (great) package, I will use:

* `addLegendNumeric` for color gradients
* `addLegendSize` for symbols varying in size (and optionally color or fill)
* `addLegendSymbols` for symbols varying in shape and/or color/fill)
* `addLegendLine` for line width (and optionally color or fill)

Is `addLegendImage` the most flexible? Is that correct or do you have suggestions?

Is it possible to generate symbols with `makeSymbol` and feed that into `addLegendImage`? If so, I would consider that (because it gives more options. e.g. to vary size, color and shape at the same time.

Btw, can I show a label for missing values in the `addLegendNumeric`?

**Comment by mtennekes** [comment]
Just playing with `addLegendImage` in combination with `makeSymbol`: awesome! Just what I need.
From the source code of `makeSymbol` I figured out how to change the stroke width: `'stroke-width' = 0.1`. Why not just add an argument `strokeWidth`?

**Comment by tomroh** [comment]
There are some helper functions too: https://roh.engineering/posts/2021/05/map-symbols-and-size-legends-for-leaflet/

e.g. `makeSymbolSize`

Instead of listing all [presentation attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation) out as arguments, you can use `...` to pass them on. `strokeWidth` is needed for some internal alignment and sizing calculations and I was trying to create a consistent "naming" convention with the "leaflet" package which I wasn't a fan of `weight`.

**Comment by tomroh** [comment]
I'm thinking of adding functionality to `addLegendSize` where you can pass the breaks as a named list e.g. `c(small = 10, medium = 20, large = 30)`.  The names would be the label/text.

**Comment by chrispmad** [comment]
I was looking for exactly this functionality in addLegendSize. Thank you, @tomroh, for this superb package and for adding features like this!

**Comment by tomroh** [comment]
a75fd0f700991fa39f79e3614ea9e87b8680a250

**Comment by tomroh** [comment]
> Can the legend labels be specified in addLegendSize? I'd like to be able to specify any text (e.g. "Very large", "Large", "Medium", > "Small") for the symbol sizes.
> Btw, can I show a label for missing values in the `addLegendNumeric`?

Moving this to #62. The `addLegendNumeric` is more complex than the other legends and spacing labels becomes an issue for overriding the breaks.

This is complete for other legend functions.
