### ISSUE TITLE
Horizontal addLegendNumeric Has Poor Alignment Between Gradient and Labels

### ISSUE THREAD

**Issue by CIOData** [tomroh/leaflegend#79]
I am using addLegendNumeric in a dynamic Shiny dashboard environment where the title may extend further than the set width. Everything adjusts accordingly with the exception of the color gradient. Is there a way to allow for dynamic widths?

Code:

```
  addLegendNumeric(
      layerId = 'polyLegend',
      position = 'topleft', 
      pal = pal,
      values = dat2$value,
      tickWidth = 2,
      tickLength = 6,
      naLabel = 'No Data',
      orientation = 'horizontal',
      width = 150,
      height = 20,
      title = data_title,
      numberFormat = if (unique(dat2$fmt) == 'int'){
          function(x) {
              prettyNum(x, big.mark = ",", scientific = FALSE, digits = 1)
              }
          } else {
              function(x) {
                  paste0(round(x * 100, 1), "%")
              }
              }
      ) 
```

Output:

![Screenshot 2023-12-26 231112](https://github.com/tomroh/leaflegend/assets/92124239/f659a839-4bd4-4188-9a0e-020ed9d9ca79)

**Comment by tomroh** [comment]
What version of leaflegend are you using and the "dynamic" here is the text header size?

**Comment by CIOData** [comment]
I'm using leaflegend 1.1.1. Yes, the map coloring adjusts based on user variable selection. If the title of the variable selected exceeds the pre-specified width of the legend, then it drags the upper tick mark out with it. If the title is shorter, everything renders fine.

**Comment by tomroh** [comment]
Can you try with the latest version on GitHub? I made changes to the backend of addLegendNumeric a couple months ago that should resolve this.

**Comment by CIOData** [comment]
Yes, this did resolve the issue. Thank you. I look forward to this being in the stable release, as we're currently using a hacky work around in our distributed code.

**Comment by tomroh** [comment]
It will be in the next release which I'll put out soon.

**Comment by tomroh** [comment]
On it's way to CRAN
